steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.cloudrun', '-t', 'gcr.io/tensorops-playground/agent-scrum', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/tensorops-playground/agent-scrum']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - agent-scrum
      - --image=gcr.io/tensorops-playground/agent-scrum
      - --platform=managed
      - --region=us-central1
      - --allow-unauthenticated
      - --session-affinity
      - --min-instances=0
      - --max-instances=5
      - --port=8080
      - --memory=1Gi
      - --cpu=1
      - --timeout=300
images:
  - 'gcr.io/tensorops-playground/agent-scrum'
