"""
Agent Scrum - AI Multi-Agent Demo

Main FastAPI application for multi-agent collaboration on software development.
"""
import logging
import os
import uuid
from contextlib import asynccontextmanager
from fastapi import FastAPI, WebSocket, WebSocketDisconnect, Request, Response
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from starlette.middleware.base import BaseHTTPMiddleware

from app.session import session_manager, _current_session, _current_api_key
from app.api.routes import stories, tasks, agents, prd, workflow, chat, agent_management, pipeline, epics, simulate
from app.api.routes import settings as settings_routes
from app.api.websocket.manager import manager

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

SESSION_HEADER = "X-Session-Id"


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Application lifespan manager."""
    # Startup
    await session_manager.start_reaper()
    print("[Startup] Agent Scrum started with session isolation")
    yield
    # Shutdown
    await session_manager.stop_reaper()
    await session_manager.destroy_all()


app = FastAPI(
    title="Agent Scrum - AI Multi-Agent Demo",
    description="Multi-agent collaboration on software development workflow using LangGraph",
    version="0.3.0",
    lifespan=lifespan
)

# CORS — allow all origins (Cloud Run provides its own domain)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class SessionMiddleware(BaseHTTPMiddleware):
    """Extract session_id from X-Session-Id header (generated by browser per tab), set contextvars."""

    async def dispatch(self, request: Request, call_next):
        # Skip for WebSocket (handled separately) and static files
        if request.url.path.startswith("/ws") or request.url.path.startswith("/assets"):
            return await call_next(request)

        # Session ID comes from the browser (sessionStorage-backed header).
        # If missing (e.g. health check), generate an ephemeral one.
        session_id = request.headers.get(SESSION_HEADER)
        if not session_id:
            session_id = uuid.uuid4().hex

        # Get or create the session
        session = await session_manager.get_or_create(session_id)

        # Set contextvars
        session_token = _current_session.set(session)
        api_key = request.headers.get("X-Api-Key") or None
        api_key_token = _current_api_key.set(api_key)

        try:
            response = await call_next(request)
            return response
        finally:
            _current_session.reset(session_token)
            _current_api_key.reset(api_key_token)


app.add_middleware(SessionMiddleware)

# Include routers
app.include_router(stories.router)
app.include_router(tasks.router)
app.include_router(agents.router)
app.include_router(prd.router)
app.include_router(workflow.router)
app.include_router(chat.router)
app.include_router(settings_routes.router)
app.include_router(agent_management.router)
app.include_router(pipeline.router)
app.include_router(epics.router)
app.include_router(simulate.router)


@app.get("/api/health")
async def health_check():
    return {"status": "healthy"}


@app.delete("/api/session")
async def delete_session(request: Request):
    """Explicitly destroy the current session."""
    session_id = request.headers.get(SESSION_HEADER)
    if session_id:
        await manager.remove_session(session_id)
        await session_manager.destroy(session_id)
    return Response(content='{"success": true}', media_type="application/json")


@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    # Session ID comes from query param (set by frontend from sessionStorage)
    session_id = websocket.query_params.get("session_id", "global")

    # Ensure session exists and set contextvar for any downstream code
    session = await session_manager.get_or_create(session_id)
    token = _current_session.set(session)

    try:
        await manager.connect(websocket, session_id)
        try:
            while True:
                data = await websocket.receive_text()
        except WebSocketDisconnect:
            await manager.disconnect(websocket, session_id)
    finally:
        _current_session.reset(token)


# Mount static files for SPA serving (must be LAST)
_frontend_dist = os.path.join(os.path.dirname(__file__), "..", "frontend-dist")
if os.path.isdir(_frontend_dist):
    app.mount("/", StaticFiles(directory=_frontend_dist, html=True), name="spa")
